### ISSUE TITLE
Gears

### ISSUE THREAD

**Issue by IQuick143** [IQuick143/bevy_jam_5#16]
Nothing novel, effectively just a cycle with no vertices.
Could be useful for levels heavy on linkages.

Possibly don't even need special code, just make sure that the code and UI work for a vertex-less cycle. (And possibly add a validation lint warning against vertex-less cycles with no linkages.)

**Comment by IWonderWhatThisAPIDoes** [comment]
I *miiight* be currently rewriting the level parser, so I can just drop this requirement right away

**Comment by IWonderWhatThisAPIDoes** [comment]
The game no longer crashes when turning a cycle with no vertices. If a cycle has one vertex, objects on it do not animate properly (they appear to be standing still), but I expect that to be resolved when we rewrite animation code
